/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import Info.Style;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Simen
 */
public class LeftPanel extends javax.swing.JPanel {

    JLabel selected;
    ArrayList<JButton> buttons;
    JLabel label1;

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        buttons = new ArrayList<>();
        initComponents();
        initButtons();
        setSize(100, 100);
        setName("Left");
        label1 = new JLabel();
        label1.setBounds(125, 84, 45, 10);
        label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/smallProgressWhite.gif"))); // NOI18N
        add(label1);
        initSelectedComp();
        JLabel background = new JLabel();
        background.setBounds(0, 0, 202, 1000);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/leftBack223.png")));
        defaultButtons();
        add(background);
        label1.setVisible(false);
        libraryBut1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        libraryBut1.setForeground(new java.awt.Color(255, 255, 255));
        libraryBut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/libraryWhite.png")));
    }

    public void setLoadVis() {
        if (label1.isVisible()) {
            label1.setVisible(false);
        } else {
            label1.setVisible(true);
        }

    }

    private void initButtons() {
        buttons.add(adBut);
        buttons.add(libraryBut);
        buttons.add(recBut);
        buttons.add(searchBut);
        buttons.add(libraryBut1);
    }

    private void defaultButtons() {
        for (JButton button : buttons) {
            button.setFont(new java.awt.Font("Calibri Light", 0, 14));
            button.setForeground(Style.getDefaultMenuColor());
            if (button.getText().equals("Home")) {
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/library.png")));
            }
            if (button.getText().equals("Library")) {
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/libraryIcon.png")));
            }
            if (button.getText().equals("Recently added")) {
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/recently.png")));
            }
            if (button.getText().equals("Advanced search")) {
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/test.png")));
            }

            if (button.getText().equals("Search results")) {
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/icon_search.png")));
            }


        }
    }

    private void initSelectedComp() {
        selected = new JLabel();
        selected.setBounds(0, 1, 202, 53);
        selected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/homeButA3.png")));
        add(selected);
        selected.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adBut = new javax.swing.JButton();
        libraryBut = new javax.swing.JButton();
        recBut = new javax.swing.JButton();
        searchBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        libraryBut1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(202, 293));

        adBut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        adBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/test.png"))); // NOI18N
        adBut.setText("Advanced search");
        adBut.setContentAreaFilled(false);
        adBut.setFocusPainted(false);
        adBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adBut.setIconTextGap(10);
        adBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adButActionPerformed(evt);
            }
        });

        libraryBut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        libraryBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/libraryIcon.png"))); // NOI18N
        libraryBut.setText("Library");
        libraryBut.setContentAreaFilled(false);
        libraryBut.setFocusPainted(false);
        libraryBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libraryBut.setIconTextGap(15);
        libraryBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryButActionPerformed(evt);
            }
        });
        libraryBut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                libraryButFocusLost(evt);
            }
        });

        recBut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        recBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/recently.png"))); // NOI18N
        recBut.setText("Recently added");
        recBut.setContentAreaFilled(false);
        recBut.setFocusPainted(false);
        recBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recBut.setIconTextGap(15);
        recBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recButActionPerformed(evt);
            }
        });

        searchBut.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        searchBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/icon_search.png"))); // NOI18N
        searchBut.setText("Search results");
        searchBut.setContentAreaFilled(false);
        searchBut.setFocusPainted(false);
        searchBut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchBut.setIconTextGap(15);
        searchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(61, 67, 69));
        jSeparator1.setForeground(new java.awt.Color(61, 67, 69));

        libraryBut1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        libraryBut1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/library.png"))); // NOI18N
        libraryBut1.setText("Home");
        libraryBut1.setToolTipText("");
        libraryBut1.setContentAreaFilled(false);
        libraryBut1.setFocusPainted(false);
        libraryBut1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        libraryBut1.setIconTextGap(15);
        libraryBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryBut1ActionPerformed(evt);
            }
        });
        libraryBut1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                libraryBut1FocusLost(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(61, 67, 69));
        jSeparator2.setForeground(new java.awt.Color(61, 67, 69));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(libraryBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(libraryBut1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libraryBut1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(libraryBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(recBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(adBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void libraryButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryButActionPerformed
        menuClick(libraryBut, false);
    }//GEN-LAST:event_libraryButActionPerformed

    private void recButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recButActionPerformed
        menuClick(recBut, false);
    }//GEN-LAST:event_recButActionPerformed

    public JButton getButtonRec() {
        return recBut;
    }

    public JButton getButtonAdvan() {
        return adBut;
    }

    public JButton getButtonHome() {
        return libraryBut1;
    }

    public JButton getButtonLib() {
        return libraryBut;
    }

    public JButton getButtonSearch() {
        return searchBut;
    }
    private void adButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adButActionPerformed
        menuClick(adBut, false);
    }//GEN-LAST:event_adButActionPerformed

    private void libraryButFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_libraryButFocusLost
    }//GEN-LAST:event_libraryButFocusLost

    private void searchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButActionPerformed
        menuClick(searchBut, false);
    }//GEN-LAST:event_searchButActionPerformed

    private void libraryBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryBut1ActionPerformed
        menuClick(libraryBut1, false);
    }//GEN-LAST:event_libraryBut1ActionPerformed

    private void libraryBut1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_libraryBut1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_libraryBut1FocusLost

    public JButton getButton() {
        return searchBut;
    }

    public void menuClick(JButton button, boolean manual) {
        defaultButtons();
        button.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));


        if (!selected.isVisible()) {
            selected.setVisible(true);
        }
        if (libraryBut1.isFocusOwner() || button.getText().equals(libraryBut1.getText())) {
            selected.setBounds(0, 1, 202, 53);
            selected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/homeButA3.png")));
            selected.setLocation(0, 1);
            button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/libraryWhite.png")));
        } else {
            selected.setBounds(0, 12, 202, 41);
            selected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/backButa.png")));
            if (libraryBut.isFocusOwner() || button.getText().equals(libraryBut.getText())) {
                selected.setLocation(0, 68);
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/libraryIconWhite.png")));
            } else if (recBut.isFocusOwner() || button.getText().equals(recBut.getText())) {
                selected.setLocation(0, 110);
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/recentlyWhite.png")));
            } else if (adBut.isFocusOwner() || button.getText().equals(adBut.getText())) {
                selected.setLocation(0, 152);
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/testO.png")));
            } else if (searchBut.isFocusOwner() || button.getText().equals(searchBut.getText())) {
                selected.setLocation(0, 222);
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/icon_searchWhite.png")));
            }
            if (manual) {
                selected.setLocation(0, 222);
                button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/icon_searchWhite.png")));
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adBut;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton libraryBut;
    private javax.swing.JButton libraryBut1;
    private javax.swing.JButton recBut;
    private javax.swing.JButton searchBut;
    // End of variables declaration//GEN-END:variables
}
