/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import java.awt.BorderLayout;
import java.io.IOException;
import javax.swing.JTable;

/**
 *
 * @author Simen
 */
public class NewLibrary extends javax.swing.JPanel {

    /**
     * Creates new form NewLibrary
     */
    TrackPanel songPanel;
    SearchPanel searchPanel;

    public NewLibrary() throws IOException {
        initComponents();
        songPanel = new TrackPanel();
        searchPanel = new SearchPanel();
        setLayout(new BorderLayout());
        add(songPanel,BorderLayout.NORTH);
        add(searchPanel,BorderLayout.CENTER);
        searchPanel.setTags(songPanel.getTags());
    }
    
    public JTable getTable() {
        return searchPanel.getTable();
    }
    
    boolean isLink() {
        return searchPanel.isLink();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
