/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Simen
 */
public class SaveDialog extends javax.swing.JDialog {

    int counter = 0;
    Thread thread;
    JLabel textInfo;
    JLabel suc;
    MetaEdit metaEdit;
    JLabel progress;
    int simluationSpeed = 1000;
    JButton button;
    /**
     * Creates new form SaveDialog
     */
    public SaveDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);

        initComponents();
        setSize(490, 100);
        setLocationRelativeTo(null);
        textInfo = new JLabel();
        textInfo.setBounds(55, 50, 70, 10);
        textInfo.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        textInfo.setText("Saving...");
        jPanel1.add(textInfo);
        //textInfo.setVisible(false);

        suc = new JLabel();
        suc.setBounds(410, 45, 20, 20);
        suc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/sucess3.png")));
        jPanel1.add(suc);
        suc.setVisible(false);
        progress = new JLabel();
        progress.setBounds(100, 50, 0, 10);
        progress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/prosessedBar.png")));
        jPanel1.add(progress);

        button = new JButton();
        button.setBounds(190, 50, 120, 28);
        button.setText("OK");
        jPanel1.add(button);
        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveSmall.png"))); // NOI18N
        button.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveOverSmall.png")));
        button.setVisible(false);
        button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));


        button.setContentAreaFilled(false);

        button.setFocusPainted(false);


        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

    }

    public void getMeta(MetaEdit m) {
        metaEdit = m;

    }

    public void save() {

        thread = new Thread(new Runnable() {
            public void run() {

                textInfo.setVisible(true);
                while (progress.getSize().width < 300) {
                    if (counter == simluationSpeed) {
                        progress.setSize(progress.getSize().width + 1, 10);

                        simluationSpeed += 10000;
                        counter = 0;
                    }

                    counter++;
                }
                textInfo.setText("Saved");
                suc.setVisible(true);
                suc.setLocation(suc.getLocation().x, suc.getLocation().y - 20);
                progress.setLocation(progress.getLocation().x, progress.getLocation().y - 20);
                textInfo.setLocation(textInfo.getLocation().x, textInfo.getLocation().y - 20);
                button.setVisible(true);

            }
        });
        try {
            Thread.sleep(1000 / 30);
        } catch (InterruptedException ex) {
            Logger.getLogger(MetaEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        thread.start();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        metaEdit.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveDialog dialog = new SaveDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
