/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import Handlers.TableHandler;
import Handlers.TableHandler.Song;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 *
 * @author Simen
 */
public class StatisticTop extends javax.swing.JPanel {

    /**
     * Creates new form StatisticTop
     */
    int x = 10;
    final int MAX = 200;
    TableHandler tableHandler;
    
    public StatisticTop() throws SQLException {
        initComponents();
        tableHandler = new TableHandler();
        refreshStat();
        
    }
    
    public void refreshStat() throws SQLException {
        
        
        tableHandler.getMostPopular(jTable1);
        System.out.println(tableHandler.getPopular().size());
        for (final Song s : tableHandler.getPopular()) {
            int perc = s.popularity * 2;
            
            jPanel2.add(addGraphPerc(perc));
            jPanel2.setSize(new Dimension(jPanel2.getSize().width + 50, jPanel2.getSize().height));
            final JLabel temp = addGraph(perc);
            jPanel2.add(temp);
            temp.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel1MouseClicked(evt, s);
                }
                
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jLabel1MouseEntered(evt, temp);
                }
                
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    jLabel1MouseExited(evt, temp);
                }
            });
        }
        
    }
    
    private JLabel addGraph(int size) {
        JLabel bar = new JLabel();
        if (size == 0) {
            size = 10;
            bar.setEnabled(false);
            bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/percentageZero.png")));
        } else {
            bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/percentage.png")));
        }
        bar.setBounds(x, 100 + (MAX - size), 25, size);
        
        x += 40;
        return bar;
    }
    
    private JLabel addGraphPerc(int size) {
        JLabel percentIndicator = new JLabel();
        
        
        percentIndicator.setForeground(new Color(102, 102, 102));
        if (size != 0) {
            percentIndicator.setBounds(x + 2, 80 + (MAX - size), 45, 20);
        } else {
            percentIndicator.setBounds(x + 2, 270, 45, 20);
        }
        
        percentIndicator.setText(size / 2 + " %");
        return percentIndicator;
    }
    
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt, JLabel label) {
        if (label.isEnabled()) {
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/percentageOver.png")));
        }
        
    }
    
    private void jLabel1MouseExited(java.awt.event.MouseEvent evt, JLabel label) {
        if (label.isEnabled()) {
            label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/percentage.png")));
        }
        
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt, Song track) {
        jLabel1.setText(track.track + " (" + track.popularity + " % of all searches)");
        jLabel2.setText("This song has appeared in " + track.raw + " search results");
        jLabel1.setForeground(new Color(51, 51, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click a bar to see info");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 14, 604, 40);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Click a bar to see info");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 60, 604, 17);

        jTabbedPane1.addTab("Graph", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setRowHeight(24);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Table", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
