/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import Handlers.Songhandler;
import database.DBConnection;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Simen
 */
public class TrackPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrackPanel
     */
    HashMap<String, JLabel> tags;
    DBConnection db;
    File file;
    String home;
    Songhandler songhandler;

    public TrackPanel() throws SQLException, FileNotFoundException, IOException {
        initComponents();
        setLayout(new BorderLayout());
        add(jPanel1, BorderLayout.CENTER);
        db = new DBConnection();
        tags = new HashMap<>();
        initTags();
        songhandler = new Songhandler();
        songhandler.loadSongInfo(6);
        songhandler.getTopInfo(tags);
        //db.getSongInfo(1, tags);

        jButton1.setEnabled(false);
        home = System.getProperty("user.home");

        file = new File(home + "\\Documents\\GitHub\\IS-302-praksisprosjekt\\NRKProsjekt\\src\\nrkprosjekt\\graphics\\albumcovsder1.jpg");

    }

    public HashMap<String, JLabel> getTags() {
        return tags;
    }

    public void fill(JLabel l, String text) {
        tags.put(text, l);
    }

    private void initTags() {
        fill(INAM, "INAM");
        fill(IART, "IART");
        fill(IGNR, "IGNR");
        fill(IKEY, "IKEY");
        fill(ISRF, "ISRF");
        fill(IMED, "IMED");
        fill(IENG, "IENG");
        fill(ITCH, "ITCH");
        fill(ISRC, "ISRC");
        fill(ICOP, "ICOP");
        fill(ISFT, "ISFT");
        fill(ICRD, "ICRD");
        fill(IALB, "IALB");
        fill(ILAN, "ILAN");
        fill(ICMT, "ICMT");
        fill(ISBJ, "ISBJ");
        fill(ILEN, "ILEN");
        fill(ICON, "ICON");
        fill(jLabel2, "PIC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        INAM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        IALB = new javax.swing.JLabel();
        IART = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IGNR = new javax.swing.JLabel();
        ICON = new javax.swing.JLabel();
        ILEN = new javax.swing.JLabel();
        IKEY = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ICMT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ILAN = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ISBJ = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ISFT = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ICOP = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ICRD = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ISRF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ISRC = new javax.swing.JLabel();
        ITCH = new javax.swing.JLabel();
        IENG = new javax.swing.JLabel();
        IMED = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(53, 53, 53));

        INAM.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        INAM.setForeground(new java.awt.Color(255, 255, 255));
        INAM.setText("Mabvuto");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Country");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveSmall.png"))); // NOI18N
        jButton1.setText("OPEN FILE");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveOverSmall.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveSmall.png"))); // NOI18N
        jButton3.setText("EXTRACT FILE");
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveOverSmall.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        IALB.setForeground(new java.awt.Color(255, 255, 255));
        IALB.setText("Album");

        IART.setForeground(new java.awt.Color(255, 255, 255));
        IART.setText("Artist");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Genre");

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Length");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Keywords");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Album");

        IGNR.setForeground(new java.awt.Color(255, 255, 255));
        IGNR.setText("Album");

        ICON.setForeground(new java.awt.Color(255, 255, 255));
        ICON.setText("Album");

        ILEN.setForeground(new java.awt.Color(255, 255, 255));
        ILEN.setText("Album");

        IKEY.setForeground(new java.awt.Color(255, 255, 255));
        IKEY.setText("Album");

        jPanel2.setBackground(new java.awt.Color(53, 53, 53));

        jLabel2.setBackground(new java.awt.Color(53, 53, 53));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/art.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(206, 220));
        jPanel2.add(jLabel2);

        jPanel3.setBackground(new java.awt.Color(53, 53, 53));

        jPanel4.setBackground(new java.awt.Color(53, 53, 53));

        ICMT.setForeground(new java.awt.Color(255, 255, 255));
        ICMT.setText("jLabel1");

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Comments");

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Language");

        ILAN.setForeground(new java.awt.Color(255, 255, 255));
        ILAN.setText("jLabel1");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Subjects");

        ISBJ.setForeground(new java.awt.Color(255, 255, 255));
        ISBJ.setText("jLabel1");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Software");

        ISFT.setForeground(new java.awt.Color(255, 255, 255));
        ISFT.setText("jLabel1");

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Copyright");

        ICOP.setForeground(new java.awt.Color(255, 255, 255));
        ICOP.setText("jLabel1");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Creation date");

        ICRD.setForeground(new java.awt.Color(255, 255, 255));
        ICRD.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(ICMT))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(3, 3, 3)
                        .addComponent(ILAN))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(4, 4, 4)
                        .addComponent(ICRD))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(3, 3, 3)
                        .addComponent(ICOP))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(ISFT))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(9, 9, 9)
                        .addComponent(ISBJ)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(ICRD))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(ICOP))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(ISFT))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(ISBJ))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(ILAN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ICMT))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(53, 53, 53));

        jPanel5.setBackground(new java.awt.Color(53, 53, 53));
        jPanel5.setPreferredSize(new java.awt.Dimension(134, 182));

        ISRF.setForeground(new java.awt.Color(255, 255, 255));
        ISRF.setText("jLabel1");

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Digitization Source");

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Engineer");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Sampled by");

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Supplier");

        ISRC.setForeground(new java.awt.Color(255, 255, 255));
        ISRC.setText("jLabel1");

        ITCH.setForeground(new java.awt.Color(255, 255, 255));
        ITCH.setText("jLabel1");

        IENG.setForeground(new java.awt.Color(255, 255, 255));
        IENG.setText("jLabel1");

        IMED.setForeground(new java.awt.Color(255, 255, 255));
        IMED.setText("Album");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Original Medium");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(IMED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(ISRF))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(8, 8, 8)
                        .addComponent(IENG))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(ITCH))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(ISRC)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(IMED))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(ISRF))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(IENG))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(ITCH))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ISRC))
                .addGap(0, 88, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(INAM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IART, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(IALB))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(13, 13, 13)
                                        .addComponent(IKEY))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(7, 7, 7)
                                                .addComponent(ILEN))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(11, 11, 11)
                                                .addComponent(IGNR))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(1, 1, 1)
                                                .addComponent(ICON)))
                                        .addGap(27, 27, 27)))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IART, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(INAM))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IALB)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(IGNR))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ICON))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ILEN))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(IKEY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        File file2 = new File(home + "\\Documents\\GitHub\\IS-302-praksisprosjekt\\NRKProsjekt\\src\\nrkprosjekt\\graphics\\null.jpg");
        Path p5 = Paths.get(System.getProperty("user.home"), "logs", "foo.log");

        System.out.println(p5);
        if (file.exists()) {
            try {
                Desktop.getDesktop().open(file);
            } catch (IOException ex) {
                Logger.getLogger(TrackPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            ;
        } else {
            try {
                //extracte
                Desktop.getDesktop().open(file2);
            } catch (IOException ex) {
                Logger.getLogger(TrackPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        };

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //hente fra datasea
        //putte linken inn i datBASE
        File newFile = new File("desktop/simen");
        //putt på skirveborder
        file = newFile;
        jButton1.setEnabled(true);




    }//GEN-LAST:event_jButton3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IALB;
    private javax.swing.JLabel IART;
    private javax.swing.JLabel ICMT;
    private javax.swing.JLabel ICON;
    private javax.swing.JLabel ICOP;
    private javax.swing.JLabel ICRD;
    private javax.swing.JLabel IENG;
    private javax.swing.JLabel IGNR;
    private javax.swing.JLabel IKEY;
    private javax.swing.JLabel ILAN;
    private javax.swing.JLabel ILEN;
    private javax.swing.JLabel IMED;
    private javax.swing.JLabel INAM;
    private javax.swing.JLabel ISBJ;
    private javax.swing.JLabel ISFT;
    private javax.swing.JLabel ISRC;
    private javax.swing.JLabel ISRF;
    private javax.swing.JLabel ITCH;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
