/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nrkprosjekt;

import Handlers.LoginHandler;
import Info.Style;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Simen
 */
public class UsersPanel extends javax.swing.JPanel {
    
    final int MIN_PASSWORD = 4;
    boolean exists = false;
    int editing;
    int cha;
    LoginHandler loginHandler;
    int id;

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() throws SQLException {
        initComponents();
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 11));
        loginHandler = new LoginHandler();
        loginHandler.getUsers(jTable1);
        jPanel1.setVisible(false);
        jTextField1.setName("username");
        pass.setName("password");
        addActionListeners(jTextField1);
        addActionListeners(pass);
        status.setVisible(false);
        jScrollPane1.setSize(jScrollPane1.getSize().width, 254);
        jButton1.setLocation(jButton1.getLocation().x, jButton1.getLocation().y + 100);
        jButton2.setLocation(jButton2.getLocation().x, jButton2.getLocation().y + 100);
        
        
        
    }
    
    private void addActionListeners(final JTextField j) {
        j.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt, j);
            }
            
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt, j);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(39, 46, 48));
        setPreferredSize(new java.awt.Dimension(300, 450));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 170, 221));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Users");
        add(jLabel1);
        jLabel1.setBounds(0, 34, 300, 30);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(150, 52));

        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Admin", "All rights"},
                {"Hasha", "Read"}
            },
            new String [] {
                "User", "Rights"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 1));
        jTable1.setMinimumSize(new java.awt.Dimension(150, 52));
        jTable1.setRowHeight(26);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(21, 70, 258, 154);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveSmall.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonSaveOverSmall.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(20, 230, 120, 28);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonCancel.png"))); // NOI18N
        jButton2.setText("DELETE");
        jButton2.setContentAreaFilled(false);
        jButton2.setEnabled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(160, 230, 120, 28);

        jPanel1.setBackground(new java.awt.Color(39, 46, 48));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(61, 67, 69)));

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Username");

        jComboBox1.setBackground(new java.awt.Color(255, 102, 51));
        jComboBox1.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "[Choose rights]", "All rights", "Read" }));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonLong.png"))); // NOI18N
        jButton3.setText("CREATE USER");
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/nrkprosjekt/graphics/buttonLongOver.png"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        status.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        status.setText("User created");

        pass.setForeground(new java.awt.Color(153, 153, 153));
        pass.setText("Password");
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(20, 270, 258, 165);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        if (jPanel1.isVisible()) {
            jButton3.setText("CREATE USER");
            jScrollPane1.setSize(jScrollPane1.getSize().width, 254);
            jButton1.setLocation(jButton1.getLocation().x, jButton1.getLocation().y + 100);
            jButton2.setLocation(jButton2.getLocation().x, jButton2.getLocation().y + 100);
            jPanel1.setVisible(false);
            status.setVisible(false);
            jButton1.setText("ADD");
            doBlanks();
        } else {
            jScrollPane1.setSize(jScrollPane1.getSize().width, 154);
            
            jButton1.setLocation(jButton1.getLocation().x, 230);
            jButton2.setLocation(jButton2.getLocation().x, 230);
            jPanel1.setVisible(true);
            jButton1.setText("CANCEL");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    private void doBlanks() {
        jTextField1.setText("Username");
        pass.setText("Password");
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new Color(153, 153, 153));
        
        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setForeground(new Color(153, 153, 153));
        jComboBox1.setSelectedIndex(0);
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       loginHandler.deleteUser(id);
        jButton2.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(jTable1.getSelectedRow());
        if (jPanel1.isVisible()) {
            jButton1.setText("CANCEL");
        } else {
            jButton1.setText("ADD");
        }
        doBlanks();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jButton3.setText("UPDATE USER");
        editing = jTable1.getSelectedRow();
        status.setVisible(false);
        if (jPanel1.isVisible()) {
            jButton1.setText("CANCEL");
        } else {
            jButton1.setText("EDIT");
        }
        jButton2.setEnabled(true);
        //jPanel1.setVisible(false);
        //CHANGE THINGS
        jTable1.setSelectionBackground(new Color(51, 153, 255));
        
        String temp = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String temp2 = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String temp3 = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
        id = Integer.parseInt(temp3);
        jTextField1.setText(temp);
        jTextField1.setForeground(new Color(51, 51, 51));
        jTextField1.setBackground(new java.awt.Color(232, 255, 232));
        jComboBox1.setSelectedItem(temp2);
        // jTextField2.setText(temp2);
        //jTextField2.setForeground(new Color(51, 51, 51));
        //jTextField2.setBackground(new java.awt.Color(232, 255, 232));

        
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!jPanel1.isVisible()) {
            jButton1.setText("ADD");
            
        }
        jTable1.setSelectionBackground(new Color(230, 230, 230));
        jButton2.setEnabled(false);
        status.setVisible(false);
    }//GEN-LAST:event_formMouseClicked
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        if (jComboBox1.getSelectedItem().toString().equals("[Choose rights]")) {
            jComboBox1.setForeground(new Color(153, 153, 153));
        } else {
            jComboBox1.setForeground(new Color(51, 51, 51));
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    private void jTable1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusLost
        jTable1.setSelectionBackground(new Color(230, 230, 230));
    }//GEN-LAST:event_jTable1FocusLost
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton2.setEnabled(false);
        jButton3.setText("CREATE USER");
        for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {
            if (jTextField1.getText().equals(jTable1.getValueAt(i, 2).toString())) {
                exists = true;
                cha = i;
            }
            
        }
        status.setForeground(new Color(255, 51, 0));
        status.setVisible(true);
        String temp = jTextField1.getText();
        String temp2 = pass.getText();
        if (temp.equals("") || temp.equals("Username") || temp2.equals("") || temp2.equals("Password")) {
            status.setText("Fill out all fields");
            
        } else if (temp2.length() > 1 && temp2.length() < MIN_PASSWORD) {
            status.setText("Password is too short");
        } else if (jComboBox1.getSelectedItem().toString().equals("[Choose rights]")) {
            status.setText("Choose user rights");
            
        } else if (exists) {
            if (editing == cha) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.removeRow(cha);
                model.insertRow(cha, new Object[]{null,id,temp,temp2, jComboBox1.getSelectedItem().toString()});
                try {
                    loginHandler.updateUser(id, temp2, jComboBox1.getSelectedItem().toString(),null,false);
                } catch (SQLException ex) {
                    Logger.getLogger(UsersPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                status.setText("User '" + temp + "' updated with '" + jComboBox1.getSelectedItem().toString() + "'");
                status.setForeground(Style.getSuccessColor());
                doBlanks();
            } else {
                status.setText("User already exists");
            }
            
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{null,null,temp,temp2, jComboBox1.getSelectedItem().toString()});
            try {
                loginHandler.updateUser(id, temp2, jComboBox1.getSelectedItem().toString(),temp,true);
            } catch (SQLException ex) {
                Logger.getLogger(UsersPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            status.setText("User '" + temp + "' created with '" + jComboBox1.getSelectedItem().toString() + "'");
            status.setForeground(Style.getSuccessColor());
            doBlanks();
        }
        exists = false;
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        if (pass.getText().length() < MIN_PASSWORD) {
            pass.setBackground(new Color(255, 204, 204));
        } else if (pass.getText().length() < 8) {
            pass.setBackground(new Color(255, 255, 204));
        } else {
            pass.setBackground(new java.awt.Color(232, 255, 232));
        }
    }//GEN-LAST:event_passKeyReleased
    
    private void jTextField1FocusGained(java.awt.event.FocusEvent evt, JTextField j) {
        if (j.getText().equals("Username") || j.getText().equals("Password")) {
            j.setText("");
            j.setForeground(new Color(51, 51, 51));
        }
    }
    
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt, JTextField j) {
        if (j.getText().equals("")) {
            j.setBackground(new java.awt.Color(255, 255, 255));
            j.setForeground(new Color(153, 153, 153));
            if (j.getName().equals("username")) {
                j.setText("Username");
            } else {
                j.setText("Password");
            }
        } else {
            j.setBackground(new java.awt.Color(232, 255, 232));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
